# Generated by Django 5.0.4 on 2024-04-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tarefa',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='titulo',
            new_name='task_title',
        ),
    ]
